export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT_TYPES = "GET_PRODUCT_TYPES";
export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const RETRIEVE_ALL_PRODUCT = "RETRIEVE_ALL_PRODUCT";
export const RETRIEVE_ALL_VALID_PRODUCT = "RETRIEVE_ALL_VALID_PRODUCT";
export const RETRIEVE_ALL_EXPIRED_PRODUCT = "RETRIEVE_ALL_EXPIRED_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCT  = "DELETE_ALL_PRODUCT";
export const FIND_VALID_PRODUCT_BY_TYPE_MFD  = "FIND_VALID_PRODUCT_BY_TYPE_MFD";
export const FIND_EXPIRED_PRODUCT_BY_TYPE_MFD  = "FIND_EXPIRED_PRODUCT_BY_TYPE_MFD";